#!/bin/sh

#TODO: change wording output file to output path

# Function to display usage
usage() {
  echo "Usage: $0 [-o output_file] file_name"
  echo "Options:"
  echo "  -o <output_file>  Specify output file (optional)"
  echo "  -h                Display this help message"
  exit 1
}

#TODO: use global variable for output file
#TODO: handle exceptions for creating, entering and removing temp dir
# Extract function for different file types
extract_file() {
  _file="$1"
  _tool="$2"
  _options="$3"
#  _base="${file%.*}"
  
  # make new dir temp,if successful move into it otherwise exit 1
  mkdir temp && cd temp || exit 1

  if ! "$_tool" "$_options" "../$_file"; then
    cd ../
    rm -fr temp
    echo "Extraction failed or not possible for file '$_file'."
    exit 1
  fi
  # clean up
  cd ../
  mv -buv temp/* "$output_file"
  rm -r temp
  echo "File '$_file' extracted successfully."
}

# Check if any arguments provided
if [ $# -eq 0 ]; then
  usage
fi

# Variables for output file
output_file=""

#TODO: add a silent option -s. If this option is set all output is suppressed. 
#TODO: ensure exit 1 on all errors/exceptions
# Parse command options
while getopts "o:h" opt; do
  case $opt in
    o) output_file="$OPTARG" ;;
    h) usage ;;
    \?) usage ;;
  esac
done

# Remove the options parsed from the argument list
shift $((OPTIND - 1))

# Check if a file name is provided as an argument
if [ $# -eq 0 ]; then
  echo "Please provide a file name."
  usage
fi

file="$1"

# Check if the file exists
if [ ! -f "$file" ]; then
  echo "File '$file' does not exist."
  exit 1
fi

#|| [ ! -w "$output_file" ]
if [ ! "$output_file" ] ; then 
  output_file="${file%.*}"
fi

if [ ! -d "$output_file" ] ; then 
  if ! mkdir "$output_file"  ; then
    echo "Could not create '$output_file'"
    exit 1
  fi
fi

#TODO: don't pass $file use global variable
# Determine file extension and extract accordingly
case "$file" in
  *.tar.bz2)
    extract_file "$file" "tar" "xjf"
    ;;
  *.tar.gz | *.tgz)
    extract_file "$file" "tar" "xzf"
    ;;
  *.bz2)
    extract_file "$file" "bunzip2" "-k"
    ;;
  *.rar)
    extract_file "$file" "unrar" "x"
    ;;
  *.gz)
    extract_file "$file" "gunzip" "-k"
    ;;
  *.tar)
    extract_file "$file" "tar" "xf"
    ;;
  *.tbz2)
    extract_file "$file" "tar" "xjf"
    ;;
  *.zip)
    extract_file "$file" "unzip" "-q"
    ;;
  *.Z)
    extract_file "$file" "uncompress" "-k"
    ;;
  *.7z)
    extract_file "$file" "7z" "x"
    ;;
  *)
    echo "File extension not supported for file '$file'."
    exit 1
    ;;
esac

echo "Have a nice day!"



