#!/usr/bin/env bash
#thanks to https://gist.github.com/davegallant/277021b86161035e812082e73ae12fb7

# This script clones all repos in a GitHub org
# It requires the GH CLI: https://cli.github.com
# It can be re-run to collect new repos and pull the latest changes

set -euo pipefail

USAGE="Usage: gh-clone-org <user|org>"

[[ $# -eq 0 ]] && echo >&2 "missing arguments: ${USAGE}" && exit 1

org=$1
limit=9999

repos="$(gh repo list "$org" -L $limit)"

repo_total="$(echo "$repos" | wc -l)"
repos_complete=0
current_dir=$(pwd)
echo

echo "$repos" | while read -r repo; do
        repo_name="$(echo "$repo" | cut -f1)"
        echo "$repo_name"
        # check if repo_name is a directory clone if no pull if yes
        if [ -d "$repo_name" ]; then
                echo "$repo_name exists pulling latest changes"
                cd "$repo_name" &&
                git pull &&
                cd "$current_dir"
        else
                echo "cloning $repo_name"
                gh repo clone "$repo_name" "$repo_name" -- -q 2>/dev/null  
        fi

        repos_complete=$((repos_complete + 1))
done

echo "Finished cloning/updating all $repo_total repos in $org."
