#!/usr/bin/env bash
#thanks to https://gist.github.com/davegallant/277021b86161035e812082e73ae12fb7

# This script clones all repos in a GitHub org
# It requires the GH CLI: https://cli.github.com
# It can be re-run to collect new repos and pull the latest changes

set -euo pipefail

USAGE="Usage: gh-clone-org <user|org>"

[[ $# -eq 0 ]] && echo >&2 "missing arguments: ${USAGE}" && exit 1

org=$1
limit=9999

repos="$(gh repo list "$org" -L $limit)"

repo_total="$(echo "$repos" | wc -l)"
repos_complete=0
current_dir=$(pwd)
echo

echo "$repos" | while read -r repo; do
        repo_name="$(echo "$repo" | cut -f1)"
        echo "$repo_name"
        # check if repo_name is a directory clone if no pull if yes
        if [ -d "$repo_name" ]; then
                echo "$repo_name exists pulling latest changes"
                cd "$repo_name" 
                # if on branch feedback add and commit changes
                if git branch --show-current | grep -q feedback; then
                        git commit -a -m "feedback" 
                fi
               # determine if branch main or master exists and switch to it
                if git show-ref --verify --quiet refs/heads/main; then
                        git switch main
                elif git show-ref --verify --quiet refs/heads/master; then
                        git switch master
                fi
                git pull &&
                # determine if branch feedback exists if yes switch to it else create it and switch to it
                if git show-ref --verify --quiet refs/heads/feedback; then
                        git switch feedback
                else
                        git switch -c feedback
                fi
                cd "$current_dir"
        else
                echo "cloning $repo_name"
                gh repo clone "$repo_name" "$repo_name" -- -q 2>/dev/null &&
                git switch -c feedback
        fi

        repos_complete=$((repos_complete + 1))
done

echo "Finished cloning/updating all $repo_total repos in $org."
